### PR TITLE
[FEATURE] vg workflow CAT-143

### PR DESCRIPTION
**Pull request by shtrom**

### CODE REVIEW

**Comment by ttton** [comment]
This has been open for a long time, is it still applicable in its current state or does it require changes?

**Comment by shtrom** [comment]
I think we should merge. I'll fix the conflicts.

**Comment by shtrom** [comment]
Hum, just realised the region-handling is incorrect as compared to other SDKs. I'll need to rework this, and update the Travis jobs.

**Review by rhiannon-eldridge-lrn — APPROVED** [review]
LGTM 👍

**Pull request merged**
