### PR TITLE
[TEST] Add codeclimate config for ruby

### PR DESCRIPTION
**Pull request by eoghanmcilwaine**
LRN-22776

### CODE REVIEW

**Comment by eoghanmcilwaine** [comment]
Hey @shtrom, would it make sense to add a Gemfile.lock to this repo? The codeclimate [bundler-audit plugin](https://docs.codeclimate.com/docs/bundler-audit) seems to require it.

**Comment by shtrom** [comment]
On 16 May 2019 2:09:53 pm AEST, Eoghan McIlwaine <notifications@github.com> wrote:
>Hey @shtrom, would it make sense to add a Gemfile.lock to this repo?
>The codeclimate [bundler-audit
>plugin](https://docs.codeclimate.com/docs/bundler-audit) seems to
>require it. 

Yeah, I think it would be good.
-- 
Olivier Mehani <olivier.mehani@learnosity.com>
Sent from my mobile, please excuse my brevity

**Comment by shtrom** [comment]
On 16 May 2019 2:09:53 pm AEST, Eoghan McIlwaine <notifications@github.com> wrote:
>Hey @shtrom, would it make sense to add a Gemfile.lock to this repo?
>The codeclimate [bundler-audit
>plugin](https://docs.codeclimate.com/docs/bundler-audit) seems to
>require it. 

It should be updated by the release script (when there is one), same as the requirements.txt for Python.
-- 
Olivier Mehani <olivier.mehani@learnosity.com>
Sent from my mobile, please excuse my brevity

**Comment by norvin-yecla-lrn** [comment]
@shtrom Hi Olivier, I updated this PR. Please have a look.

**Pull request merged**
